config/routes.rb
Rails.application.routes.draw do

  resources :users do
    resources :orders do
      collection do
        get 'confirm' , to: "orders#confirm"
        get 'confirmend' , to: "orders#confirmend"
      end
    end
  end

  resources :items

  get 'index' , to: "main#index"
  get 'index2' , to: "main#index2"
  get 'index3' , to: "main#index3"
  get 'index4' , to: "main#index4"
  get 'index5' , to: "main#index5"
  get 'index6' , to: "main#index6"
  get 'index7' , to: "main#index7"
  get 'index8' , to: "main#index8"

  root to: "main#index"

end

app/models/item.rb
class Item < ActiveRecord::Base
end

app/models/order.rb
class Order < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
  authenticates_with_sorcery!
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  before_action :set_item, only: [:show, :edit, :update, :destroy]

  # GET /items
  # GET /items.json
  def index
    @items = Item.all
  end

  # GET /items/1
  # GET /items/1.json
  def show
  end

  # GET /items/new
  def new
    @item = Item.new
  end

  # GET /items/1/edit
  def edit
  end

  # POST /items
  # POST /items.json
  def create
    @item = Item.new(item_params)

    respond_to do |format|
      if @item.save
        format.html { redirect_to @item, notice: 'Item was successfully created.' }
        format.json { render :show, status: :created, location: @item }
      else
        format.html { render :new }
        format.json { render json: @item.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /items/1
  # PATCH/PUT /items/1.json
  def update
    respond_to do |format|
      if @item.update(item_params)
        format.html { redirect_to @item, notice: 'Item was successfully updated.' }
        format.json { render :show, status: :ok, location: @item }
      else
        format.html { render :edit }
        format.json { render json: @item.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /items/1
  # DELETE /items/1.json
  def destroy
    @item.destroy
    respond_to do |format|
      format.html { redirect_to items_url, notice: 'Item was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_item
      @item = Item.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def item_params
      params.require(:item).permit(:name, :value, :order_id, :integer)
    end
end

app/controllers/main_controller.rb
class MainController < ApplicationController
  def index
  end
  
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  before_action :set_order, only: [:show, :edit, :update, :destroy]

  # GET /orders
  # GET /orders.json
  def index
    @orders = Order.all
  end

  # GET /orders/1
  # GET /orders/1.json
  def show
  end

  # GET /orders/new
  def new
    @order = Order.new
  end

  # GET /orders/1/edit
  def edit
  end

  # POST /orders
  # POST /orders.json
  def create
    @order = Order.new()
    @num = params[:count].to_i
    @temp = 0
    @num.times do
      @order
      @temp += 1
    end
    raise Exception.new(@temp)
    respond_to do |format|
      if @order.save
        format.html { redirect_to @order, notice: 'Order was successfully created.' }
        format.json { render :show, status: :created, location: @order }
      else
        format.html { render :new }
        format.json { render json: @order.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /orders/1
  # PATCH/PUT /orders/1.json
  def update
    respond_to do |format|
      if @order.update(order_params)
        format.html { redirect_to @order, notice: 'Order was successfully updated.' }
        format.json { render :show, status: :ok, location: @order }
      else
        format.html { render :edit }
        format.json { render json: @order.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /orders/1
  # DELETE /orders/1.json
  def destroy
    @order.destroy
    respond_to do |format|
      format.html { redirect_to orders_url, notice: 'Order was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_order
      @order = Order.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def order_params
      params.require(:order).permit(:user_id)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:firstk, :lastk, :firstf, :lastf, :code, :address, :phone, :mailadress)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/main_helper.rb
module MainHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/items/_form.html.haml
= form_for @item do |f|
  - if @item.errors.any?
    #error_explanation
      %h2= "#{pluralize(@item.errors.count, "error")} prohibited this item from being saved:"
      %ul
        - @item.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :name
    = f.text_field :name
  .field
    = f.label :value
    = f.number_field :value
  .field
    = f.label :order_id
    = f.text_field :order_id
  .field
    = f.label :integer
    = f.text_field :integer
  .actions
    = f.submit 'Save'

app/views/items/edit.html.haml
%h1 Editing item

= render 'form'

= link_to 'Show', @item
\|
= link_to 'Back', items_path

app/views/items/index.html.haml
%h1 Listing items

%table
  %thead
    %tr
      %th Name
      %th Value
      %th Order
      %th Integer
      %th
      %th
      %th

  %tbody
    - @items.each do |item|
      %tr
        %td= item.name
        %td= item.value
        %td= item.order_id
        %td= item.integer
        %td= link_to 'Show', item
        %td= link_to 'Edit', edit_item_path(item)
        %td= link_to 'Destroy', item, :method => :delete, :data => { :confirm => 'Are you sure?' }

%br

= link_to 'New Item', new_item_path

app/views/items/new.html.haml
%h1 New item

= render 'form'

= link_to 'Back', items_path

app/views/items/show.html.haml
%p#notice= notice

%p
  %b Name:
  = @item.name
%p
  %b Value:
  = @item.value
%p
  %b Order:
  = @item.order_id
%p
  %b Integer:
  = @item.integer

= link_to 'Edit', edit_item_path(@item)
\|
= link_to 'Back', items_path

app/views/layouts/application.html.haml
!!! 5
%html
  %head
    %title Sona-yell
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags
%body
  %header
    %div
      .header-left
        %a{:href => "/index"}
          = image_tag 'logo2.png', class: "logo"
      .header-right
        %a.login{:href => ""} ログイン
        %a.buy{:href => "/users/new"} 注文する
      .clear

  .container
    = yield


  %footer
    %p
      .clear
      %center Copyright (C) 2015  Sona-yell .  All Rights Reserved

app/views/orders/_form.html.haml
= form_tag{controller: "order", action: "count"} do |f|
  - if @order.errors.any?
    #error_explanation
      %h2= "#{pluralize(@order.errors.count, "error")} prohibited this order from being saved:"
      %ul
        - @order.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :hoge
    = f.number_field :hoge
  .actions
    = f.submit 'Save'

app/views/orders/confirm.html.haml
.index3
  .top-wrapper
    %div
      %h1
        = image_tag 'check1.png'
        ご購入者様情報の確認
      %p
        ここに出力される
    .btns
      %a.next{:href => "/orders/confirmend"}
        .btn.message.btn 送信する
      %a.next2{:href => "/users/new"}
        .btn.message.btn2 戻る

app/views/orders/confirmend.html.haml
.index4
  .top-wrapper
    %div
      %h1
        = image_tag 'check1.png'
        送信完了
      %p
        確認メールをお送りしました。ご確認ください。
        %br
        ご購入ありがとうございました。
    .btns
      %a.next{:href => "/index"}
        .btn.message.btn HOMEへ

app/views/orders/edit.html.haml
%h1 Editing order

= render 'form'

= link_to 'Show', @order
\|
= link_to 'Back', orders_path

app/views/orders/index.html.haml
%h1 Listing orders

%table
  %thead
    %tr
      %th User
      %th
      %th
      %th

  %tbody
    - @orders.each do |order|
      %tr
        %td= order.user_id
        %td= link_to 'Show', order
        %td= link_to 'Edit', edit_order_path(order)
        %td= link_to 'Destroy', order, :method => :delete, :data => { :confirm => 'Are you sure?' }

%br

= link_to 'New Order', new_order_path

app/views/orders/new.html.haml
/ %h1 New order

/ = render 'form'

/ = link_to 'Back', orders_path



.index8
  = form_tag "/orders" do
    .top-wrapper
      .inform
        %h1
          = image_tag 'check1.png'
          商品個数
        %table
          %thead
            %tr
              %th 商品ID
              %th 商品名
              %th 価格
              %th 数量
          %tbody
            %tr
              %td.A-title A0001
              %td ベーシック3000
              %td
                初回10000円
                %br
                次回以降3000円/半年
              %td
                = number_field_tag "count", min: 0, max: 100
      .btns
        = submit_tag "次へ", class: "btn message btn"
        %a.next2{:href => "/users/new"}
          .btn.message.btn2 戻る

app/views/orders/show.html.haml
%p#notice= notice

%p
  %b User:
  = @order.user_id

= link_to 'Edit', edit_order_path(@order)
\|
= link_to 'Back', orders_path

app/views/users/_form.html.haml
= form_for @user do |f|
  - if @user.errors.any?
    #error_explanation
      %h2= "#{pluralize(@user.errors.count, "error")} prohibited this user from being saved:"
      %ul
        - @user.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :lastk
    = f.text_field :lastk
    .field
    = f.label :firstk
    = f.text_field :firstk
    .field
    = f.label :lastf
    = f.text_field :lastf
    .field
    = f.label :firstf
    = f.text_field :firstf
    .field
    = f.label :code
    = f.text_field :code
  .field
    = f.label :address
    = f.text_field :address
  .field
    = f.label :phone
    = f.text_field :phone
    .field
    = f.label :mailadress
    = f.text_field :mailadress
  .actions
    = f.submit 'Save'

app/views/users/edit.html.haml
%h1 Editing user

= render 'form'

= link_to 'Show', @user
\|
= link_to 'Back', users_path

app/views/users/index.html.haml
u%h1 Listing users

%table
  %thead
    %tr
      %th Name
      %th Address
      %th Phone
      %th Paytype
      %th
      %th
      %th

  %tbody
    - @users.each do |user|
      %tr
        %td= user.name
        %td= user.address
        %td= user.phone
        %td= user.paytype
        %td= link_to 'Show', user
        %td= link_to 'Edit', edit_user_path(user)
        %td= link_to 'Destroy', user, :method => :delete, :data => { :confirm => 'Are you sure?' }

%br

= link_to 'New User', new_user_path

app/views/users/new.html.haml
.index2
  .top-wrapper
    %div
      %div
        %h1
          = image_tag 'check1.png'
          ご注文フォーム
        %p
          Sona-yellの商品をご注文の際は、以下より必要事項をご入力の上、
          %br
          最後に下段にある「ご注文」ボタンをクリックし、ご注文ください。
      = form_for @user do |f|
        %div
          %h1
            = image_tag 'check1.png'
            注文者情報
          %table
            %thead
              %tr
                %th はじめての方
                %th
                  下のフォームにお客様のお名前、ご住所、電話番号、
                  %br
                  メールアドレスを入力し、
                  %br
                  「次へ」ボタンを押してください。
                  %br
                  必須の項目は必ず入力してください。
            %tbody
              %tr
                %td お名前　必須
                %td
                  %form{:method => "post"}
                    %p
                      姓：
                      = f.text_field :firstk
                      名：
                      = f.text_field :lastk
                    %p
                      例：山田　　　　　　　　　太郎
              %tr
                %td ふりがな　必須
                %td
                  %form{:method => "post"}
                    %p
                      せい：
                      = f.text_field :firstf
                      めい：
                      = f.text_field :lastf
                    %p
                      例　：やまだ　　　　　　　　たろう
              %tr
                %td 郵便番号　必須
                %td
                  %form{:method => "post"}
                    %p
                      = f.text_field :code
                    %p
                      例：1234567
                      %br ハイフンを挟まないでください。
              %tr
                %td 住所　必須
                %td
                  %form{:method => "post"}
                    %p
                      = f.text_field :address
                    %p
                      例：東京都品川区目黒区1-1-1山田ビル101号室
              %tr
                %td 電話番号　必須
                %td
                  %form{:method => "post"}
                    %p
                      = f.text_field :phone
                    %p
                      例：01234567890　ハイフンを挟まないでください。
              %tr
                %td メールアドレス　必須
                %td
                  %form{:method => "post"}
                    %p
                      = f.text_field :mailadress
                      %br
                      確認のため、もう一度ご記入ください
                      %br
                      = f.text_field :mailadress
                      %br
              %tr
                %td 支払い方法　
                %td
                  %form{:method => "post"}
                    %p
                      代引き
        %p
          %a.next{:href => "users/orders/new"}
            = f.submit '次へ', class: "btn message clear"

app/views/users/show.html.haml
%p#notice= notice

%p
  %b Name:
  = @user.name
%p
  %b Address:
  = @user.address
%p
  %b Phone:
  = @user.phone
%p
  %b Paytype:
  = @user.paytype

= link_to 'Edit', edit_user_path(@user)
\|
= link_to 'Back', users_path